defaults: &defaults
    working_directory: ~/appbeebatch # directory where steps will run
    docker:
      - image: circleci/node:8.11
      - image: circleci/python:3.6.1
      - image: circleci/mongo:3.6.6-jessie
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"

version: 2
jobs:
  build:                              # runs not using Workflows must have a `build` job as entry point
    <<: *defaults
    steps:                            # a collection of executable commands
      - checkout                      # special step to check out source code to working directory
      - run:
          name: prepare for mongo
          command: |
            echo "[circleci] install dependencies"
            sudo apt-get install apt-transport-https
            echo "[circleci] adding a new apt-key"
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
            echo "[circleci] updating apt"
            sudo apt-get update
            echo "[circleci] installing mongodb"
            sudo apt-get --reinstall install mongodb
            echo "[circleci] installing mongodb 3.6.6"
            sudo apt-get --reinstall install -y mongodb-org=3.6.6 mongodb-org-server=3.6.6 mongodb-org-shell=3.6.6 mongodb-org-mongos=3.6.6 mongodb-org-tools=3.6.6
            echo "[circleci] mongodb install script comleted"
      - run:
          name: check mongo
          command: mongo --version
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-          # fallback to using the latest cache if no exact match is found
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: test
          command: npm test
#      - run:
#          name: code-coverage
#          command: '../node_modules/.bin/nyc report --reporter=text-lcov'
#      - store_artifacts: # special step to save test results as as artifact
#          path: test-results.xml
#          prefix: tests
#      - store_artifacts:
#          path: coverage
#          prefix: coverage
#      - store_test_results: # special step to upload test results for display in Test Summary
#          path: test-results.xml


workflows:
  version: 2
  build:
    jobs:
      - build