defaults: &defaults
    working_directory: ~/appbeebatch # directory where steps will run
    docker:
      - image: circleci/node:8.11
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"

version: 2
jobs:
  build:                              # runs not using Workflows must have a `build` job as entry point
    <<: *defaults
    steps:                            # a collection of executable commands
      - checkout                      # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-          # fallback to using the latest cache if no exact match is found
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install mongo
          command: |
            sudo apt-get install apt-transport-https
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org
      - run:
          name: test
          command: npm test
#      - run:
#          name: code-coverage
#          command: '../node_modules/.bin/nyc report --reporter=text-lcov'
#      - store_artifacts: # special step to save test results as as artifact
#          path: test-results.xml
#          prefix: tests
#      - store_artifacts:
#          path: coverage
#          prefix: coverage
#      - store_test_results: # special step to upload test results for display in Test Summary
#          path: test-results.xml


workflows:
  version: 2
  build:
    jobs:
      - build